// Définition des catégories de Blind Test et de leurs morceaux/artistes cultes

export const CATEGORIES = [
  {
    id: 'custom_theme',
    name: 'Thème Libre (IA)',
    icon: '✨',
    color: '#ffd200',
    description: 'Tapez votre propre thème ou délire sur-mesure !',
    isCustom: true,
    country: 'FR',
    queries: [
      'Queen', 'Daft Punk', 'Michael Jackson', 'Eminem', 'Stromae',
      'Indochine', 'Ed Sheeran', 'The Weeknd', 'Jul', 'Orelsan',
      'ABBA', 'Bee Gees', 'David Bowie', 'Elton John', 'Beyonce',
      'Coldplay', 'Bruno Mars', 'Dua Lipa', 'Rihanna', 'Katy Perry'
    ],
    decoys: [
      { title: 'Bohemian Rhapsody', artist: 'Queen' },
      { title: 'One More Time', artist: 'Daft Punk' },
      { title: 'Billie Jean', artist: 'Michael Jackson' },
      { title: 'Lose Yourself', artist: 'Eminem' },
      { title: 'Shape of You', artist: 'Ed Sheeran' },
      { title: 'Blinding Lights', artist: 'The Weeknd' },
      { title: 'Tous les mêmes', artist: 'Stromae' },
      { title: 'L\'Aventurier', artist: 'Indochine' },
      { title: 'Stayin\' Alive', artist: 'Bee Gees' },
      { title: 'Rolling in the Deep', artist: 'Adele' },
      { title: 'Uptown Funk', artist: 'Bruno Mars' },
      { title: 'Dancing Queen', artist: 'ABBA' }
    ]
  },
  {
    id: 'rap_fr',
    name: 'Rap Français',
    icon: '🔥',
    color: '#ff0055',
    description: 'De NTM et IAM jusqu\'à Jul, Orelsan, PNL et Ninho',
    aiTheme: 'Le meilleur du rap français, des pionniers des années 90 aux têtes d\'affiche actuelles',
    country: 'FR',
    queries: [
      'Jul bande organisée', 'Orelsan la terre est ronde', 'PNL au dd',
      'Ninho lettre a une femme', 'Booba dkr', 'Damso macarena',
      'Nekfeu on verra', 'IAM le mia', 'Suprême NTM seine saint denis style',
      'Soprano en feu', 'SCH bande organisée', 'MC Solaar caroline',
      'Disiz j\'pète les plombs', 'Gazo die', 'Gims bella', 'Vald desaccordes',
      'Aya Nakamura djadja', 'Kaaris tchoin', 'Heuss l\'enfoire moulaga', 'PLK un peu de haine',
      'Dinos helsinki', 'Josman j\'aime bien', 'Tiakola meuda', 'Werenoi laboratoire',
      'SDM bolide allemand', 'Kery James le retour du rap francais', 'Sniper graves dans la roche',
      'Sexion d\'Assaut desole', 'Gringe qui dit mieux', 'Doc Gyneco viens voir le docteur'
    ],
    decoys: [
      { title: 'Bande organisée', artist: '13 Organisé' },
      { title: 'La terre est ronde', artist: 'Orelsan' },
      { title: 'Au DD', artist: 'PNL' },
      { title: 'Lettre à une femme', artist: 'Ninho' },
      { title: 'DKR', artist: 'Booba' },
      { title: 'Macarena', artist: 'Damso' },
      { title: 'On verra', artist: 'Nekfeu' },
      { title: 'Je danse le Mia', artist: 'IAM' },
      { title: 'Seine Saint-Denis Style', artist: 'Suprême NTM' },
      { title: 'Caroline', artist: 'MC Solaar' },
      { title: 'J\'pète les plombs', artist: 'Disiz' },
      { title: 'Djadja', artist: 'Aya Nakamura' },
      { title: 'Bella', artist: 'Gims' },
      { title: 'Die', artist: 'Gazo' },
      { title: 'Désaccordé', artist: 'Vald' },
      { title: 'Bolide allemand', artist: 'SDM' },
      { title: 'Désolé', artist: 'Sexion d\'Assaut' }
    ]
  },
  {
    id: 'annees_80',
    name: 'Années 80',
    icon: '🕺',
    color: '#ff00d4',
    description: 'Les plus grands tubes disco, synthwave et new-wave',
    aiTheme: 'Les plus grands tubes des années 80 : disco, pop internationale, synthwave, new-wave et variété française 80s',
    country: 'FR',
    queries: [
      'Michael Jackson billie jean', 'Madonna like a virgin', 'Indochine l aventurier',
      'Balavoine tous les cris les sos', 'Debut de soiree nuit de folie', 'Queen another one bites the dust',
      'Cyndi Lauper girls just want to have fun', 'Gilbert Montagne sous les sunlights des tropiques',
      'Wham wake me up before you go go', 'A-ha take on me', 'Gold ville de lumiere',
      'Eurythmics sweet dreams', 'Desireless voyage voyage', 'Partenaire Particulier',
      'Emile et Images les demons de minuit', 'Jean Schultheis confiance pour confiance',
      'Earth Wind and Fire let s groove', 'Rick Astley never gonna give you up',
      'Niagara l amour a la plage', 'Jeanne Mas en rouge et noir', 'Renaud morgane de toi',
      'Cookie Dingler femme liberee', 'Kool and the Gang celebration', 'Bonnie Tyler total eclipse of the heart',
      'George Michael careless whisper', 'The Police every breath you take'
    ],
    decoys: [
      { title: 'Billie Jean', artist: 'Michael Jackson' },
      { title: 'Like a Virgin', artist: 'Madonna' },
      { title: 'L\'Aventurier', artist: 'Indochine' },
      { title: 'Tous les cris les S.O.S', artist: 'Daniel Balavoine' },
      { title: 'Nuit de folie', artist: 'Début de Soirée' },
      { title: 'Sweet Dreams', artist: 'Eurythmics' },
      { title: 'Take On Me', artist: 'A-ha' },
      { title: 'Les Démons de minuit', artist: 'Émile et Images' },
      { title: 'Voyage Voyage', artist: 'Desireless' },
      { title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper' },
      { title: 'Wake Me Up Before You Go-Go', artist: 'Wham!' },
      { title: 'Never Gonna Give You Up', artist: 'Rick Astley' },
      { title: 'En rouge et noir', artist: 'Jeanne Mas' },
      { title: 'Sous les sunlights des tropiques', artist: 'Gilbert Montagné' }
    ]
  },
  {
    id: 'annees_90_2000',
    name: 'Années 90 & 2000',
    icon: '💿',
    color: '#00f2fe',
    description: 'L\'âge d\'or MTV, les boys bands, l\'eurodance et les hymnes 2000',
    aiTheme: 'Les hymnes inoubliables des années 90 et 2000 : eurodance, pop MTV, boys bands, pop-rock et RnB 2000',
    country: 'FR',
    queries: [
      'Britney Spears baby one more time', 'Daft Punk one more time', 'Eminem without me',
      'Manau la tribu de dana', 'Kyo derniere danse', 'Diams la boulette',
      'Shakira whenever wherever', 'Beyonce crazy in love', 'Louise Attaque j t emmene au vent',
      'Black Eyed Peas i gotta feeling', 'Linkin Park in the end', 'Avril Lavigne complicated',
      'Rihanna umbrella', 'Alizee moi lolita', 'Celine Dion pour que tu m aimes encore',
      'Gala freed from desire', 'Corona the rhythm of the night', 'Coolio gangsta s paradise',
      'Destiny s Child survivor', 'Outkast hey ya', 'Backstreet Boys everybody',
      'Aqua barbie girl', 'Lou Bega mambo no 5', 'Tragedie est ce que tu m entends'
    ],
    decoys: [
      { title: '...Baby One More Time', artist: 'Britney Spears' },
      { title: 'One More Time', artist: 'Daft Punk' },
      { title: 'Without Me', artist: 'Eminem' },
      { title: 'La Tribu de Dana', artist: 'Manau' },
      { title: 'Dernière danse', artist: 'Kyo' },
      { title: 'La Boulette', artist: 'Diam\'s' },
      { title: 'Whenever, Wherever', artist: 'Shakira' },
      { title: 'Crazy in Love', artist: 'Beyoncé' },
      { title: 'In the End', artist: 'Linkin Park' },
      { title: 'I Gotta Feeling', artist: 'Black Eyed Peas' },
      { title: 'Moi... Lolita', artist: 'Alizée' },
      { title: 'Freed from Desire', artist: 'Gala' },
      { title: 'J\'t\'emmène au vent', artist: 'Louise Attaque' },
      { title: 'Hey Ya!', artist: 'OutKast' }
    ]
  },
  {
    id: 'rock_classics',
    name: 'Rock Classics',
    icon: '🎸',
    color: '#ff9900',
    description: 'Riffs légendaires, solos mythiques et légendes du rock',
    aiTheme: 'Les grands classiques du rock : rock légendaire, hard rock, grunge, pop rock et hymnes de stade',
    country: 'US',
    queries: [
      'Queen bohemian rhapsody', 'AC DC highway to hell', 'Nirvana smells like teen spirit',
      'The Beatles let it be', 'Rolling Stones paint it black', 'Pink Floyd another brick in the wall',
      'Guns N Roses sweet child o mine', 'Red Hot Chili Peppers californication', 'Telephone ca c est vraiment toi',
      'Oasis wonderwall', 'Led Zeppelin stairway to heaven', 'The Cranberries zombie',
      'Deep Purple smoke on the water', 'The Police roxanne', 'U2 with or without you',
      'Bon Jovi livin on a prayer', 'Scorpions wind of change', 'Dire Straits sultans of swing',
      'Aerosmith dream on', 'Metallica enter sandman', 'The Clash should i stay or should i go',
      'Green Day basket case', 'Blink-182 all the small things', 'Foo Fighters everlong'
    ],
    decoys: [
      { title: 'Bohemian Rhapsody', artist: 'Queen' },
      { title: 'Highway to Hell', artist: 'AC/DC' },
      { title: 'Smells Like Teen Spirit', artist: 'Nirvana' },
      { title: 'Paint It Black', artist: 'The Rolling Stones' },
      { title: 'Sweet Child O\' Mine', artist: 'Guns N\' Roses' },
      { title: 'Californication', artist: 'Red Hot Chili Peppers' },
      { title: 'Wonderwall', artist: 'Oasis' },
      { title: 'Stairway to Heaven', artist: 'Led Zeppelin' },
      { title: 'Zombie', artist: 'The Cranberries' },
      { title: 'Smoke on the Water', artist: 'Deep Purple' },
      { title: 'Ça (C\'est vraiment toi)', artist: 'Téléphone' },
      { title: 'Livin\' on a Prayer', artist: 'Bon Jovi' },
      { title: 'Basket Case', artist: 'Green Day' }
    ]
  },
  {
    id: 'pop_internationale',
    name: 'Pop Internationale',
    icon: '✨',
    color: '#9d00ff',
    description: 'Les méga-hits mondiaux qui cartonnent sur toutes les radios',
    aiTheme: 'Les méga-hits de la pop internationale moderne des années 2010 à aujourd\'hui',
    country: 'US',
    queries: [
      'Taylor Swift shake it off', 'The Weeknd blinding lights', 'Dua Lipa levitating',
      'Bruno Mars uptown funk', 'Billie Eilish bad guy', 'Ed Sheeran shape of you',
      'Ariana Grande 7 rings', 'Coldplay viva la vida', 'Harry Styles as it was',
      'Sia chandelier', 'Justin Bieber stay', 'Katy Perry roar',
      'Lady Gaga bad romance', 'Miley Cyrus flowers', 'Imagine Dragons radioactive',
      'Maroon 5 sugar', 'Adele rolling in the deep', 'Stromae alors on danse',
      'Shawn Mendes senorita', 'Sam Smith stay with me', 'Post Malone circles',
      'Lizzo about damn time', 'Olivia Rodrigo drivers license', 'Camila Cabello havana'
    ],
    decoys: [
      { title: 'Shake It Off', artist: 'Taylor Swift' },
      { title: 'Blinding Lights', artist: 'The Weeknd' },
      { title: 'Levitating', artist: 'Dua Lipa' },
      { title: 'Uptown Funk', artist: 'Bruno Mars' },
      { title: 'Bad Guy', artist: 'Billie Eilish' },
      { title: 'Shape of You', artist: 'Ed Sheeran' },
      { title: 'As It Was', artist: 'Harry Styles' },
      { title: 'Viva La Vida', artist: 'Coldplay' },
      { title: 'Chandelier', artist: 'Sia' },
      { title: 'Flowers', artist: 'Miley Cyrus' },
      { title: 'Bad Romance', artist: 'Lady Gaga' },
      { title: 'Rolling in the Deep', artist: 'Adele' },
      { title: 'Havana', artist: 'Camila Cabello' }
    ]
  },
  {
    id: 'disney_dessins_animes',
    name: 'Disney & Enfance',
    icon: '🏰',
    color: '#00e5ff',
    description: 'Les plus beaux classiques d\'animation Disney et génériques cultes',
    aiTheme: 'Les plus grandes chansons de films d\'animation Disney et génériques cultes en version française',
    country: 'FR',
    queries: [
      'Disney le roi lion histoire de la vie',
      'Disney la reine des neiges liberee delivree',
      'Disney aladdin ce reve bleu',
      'Disney tarzan entre deux mondes',
      'Pokemon un jour je serai le meilleur dresseur',
      'Disney hercule de zero en heros',
      'Disney vaiana le bleu lumiere',
      'Disney mulan comme un homme',
      'Disney le livre de la jungle il en faut peu pour etre heureux',
      'Disney la belle et la bete c est la fete',
      'Disney raiponce ou est la vraie vie',
      'Les Mysterieuses Cites d or generique',
      'Disney encanto ne parlons pas de bruno',
      'Disney la petite sirene sous l ocean',
      'Disney pocahontas l air du vent',
      'Disney les aristochats tout le monde veut devenir un cat',
      'Disney toy story je suis ton ami',
      'Disney cendrillon bibbidi bobbidi boo',
      'Disney la princesse et la grenouille au bout du reve',
      'Disney pinocchio quand on prie la bonne etoile',
      'Disney zootopie try everything',
      'Capitaine Flam generique',
      'Inspecteur Gadget generique'
    ],
    decoys: [
      { title: 'L\'Histoire de la vie', artist: 'Le Roi Lion' },
      { title: 'Ce rêve bleu', artist: 'Aladdin' },
      { title: 'Libérée, délivrée', artist: 'La Reine des Neiges' },
      { title: 'Il en faut peu pour être heureux', artist: 'Le Livre de la Jungle' },
      { title: 'Comme un homme', artist: 'Mulan' },
      { title: 'Sous l\'océan', artist: 'La Petite Sirène' },
      { title: 'Hakuna Matata', artist: 'Le Roi Lion' },
      { title: 'Le Bleu lumière', artist: 'Vaiana' },
      { title: 'Être un homme comme vous', artist: 'Le Livre de la Jungle' },
      { title: 'Histoire éternelle', artist: 'La Belle et la Bête' },
      { title: 'Tout le monde veut devenir un cat', artist: 'Les Aristochats' },
      { title: 'De zéro en héros', artist: 'Hercule' },
      { title: 'L\'Air du vent', artist: 'Pocahontas' },
      { title: 'Je suis ton ami', artist: 'Toy Story' },
      { title: 'Ne parlons pas de Bruno', artist: 'Encanto' },
      { title: 'Attrapez-les tous !', artist: 'Pokémon' }
    ]
  },
  {
    id: 'cinema_series',
    name: 'Cinéma & Séries',
    icon: '🎬',
    color: '#e6c800',
    description: 'Bandes originales légendaires du grand et du petit écran',
    aiTheme: 'Les bandes originales et thèmes musicaux cultes du cinéma et des séries TV',
    country: 'US',
    queries: [
      'John Williams star wars main theme', 'Hans Zimmer pirates of the caribbean',
      'John Williams harry potter hedwig theme', 'Ramin Djawadi game of thrones',
      'Hans Zimmer gladiator now we are free', 'Howard Shore the lord of the rings concerning hobbits',
      'Hans Zimmer interstellar main theme', 'Ennio Morricone the good the bad and the ugly',
      'John Williams jurassic park theme', 'Monty Norman james bond theme',
      'Alan Silvestri the avengers theme', 'Clint Mansell requiem for a dream lux aeterna',
      'Brad Fiedel the terminator theme', 'John Williams indiana jones theme',
      'Lalo Schifrin mission impossible theme', 'Henry Mancini pink panther theme',
      'Vangelis chariots of fire', 'Bill Conti rocky gonna fly now'
    ],
    decoys: [
      { title: 'Star Wars (Main Theme)', artist: 'John Williams' },
      { title: 'He\'s a Pirate', artist: 'Hans Zimmer (Pirates des Caraïbes)' },
      { title: 'Hedwig\'s Theme', artist: 'John Williams (Harry Potter)' },
      { title: 'Game of Thrones (Main Theme)', artist: 'Ramin Djawadi' },
      { title: 'Now We Are Free', artist: 'Hans Zimmer (Gladiator)' },
      { title: 'Concerning Hobbits', artist: 'Howard Shore (Le Seigneur des Anneaux)' },
      { title: 'The Pink Panther Theme', artist: 'Henry Mancini' },
      { title: 'James Bond Theme', artist: 'Monty Norman' },
      { title: 'Mission Impossible Theme', artist: 'Lalo Schifrin' },
      { title: 'The Good, the Bad and the Ugly', artist: 'Ennio Morricone' },
      { title: 'Jurassic Park Theme', artist: 'John Williams' },
      { title: 'The Avengers Theme', artist: 'Alan Silvestri' }
    ]
  },
  {
    id: 'variete_francaise',
    name: 'Variété Française',
    icon: '🍷',
    color: '#00d26a',
    description: 'Les grands classiques de la chanson et du patrimoine français',
    aiTheme: 'Les grands classiques incontournables du patrimoine de la chanson et variété française',
    country: 'FR',
    queries: [
      'Jean-Jacques Goldman envole-moi', 'Renaud des que le vent soufflera',
      'Francis Cabrel la corrida', 'Johnny Hallyday allumer le feu',
      'Charles Aznavour la boheme', 'Daniel Balavoine je ne suis pas un heros',
      'Michel Sardou les lacs du connemara', 'Jacques Brel ne me quitte pas',
      'Claude Francois alexandrie alexandra', 'Vianney beau-papa',
      'Florent Pagny savoir aimer', 'Christophe aline', 'Michel Polnareff lettre a france',
      'Serge Gainsbourg la javanaise', 'Joe Dassin l ete indien', 'Maxime Le Forestier san francisco',
      'Patrick Bruel casser la voix', 'Julien Clerc ma preference', 'Alain Souchon foule sentimentale'
    ],
    decoys: [
      { title: 'Envole-moi', artist: 'Jean-Jacques Goldman' },
      { title: 'Dès que le vent soufflera', artist: 'Renaud' },
      { title: 'La Corrida', artist: 'Francis Cabrel' },
      { title: 'Allumer le feu', artist: 'Johnny Hallyday' },
      { title: 'La Bohème', artist: 'Charles Aznavour' },
      { title: 'Je ne suis pas un héros', artist: 'Daniel Balavoine' },
      { title: 'Les Lacs du Connemara', artist: 'Michel Sardou' },
      { title: 'Ne me quitte pas', artist: 'Jacques Brel' },
      { title: 'Alexandrie Alexandra', artist: 'Claude François' },
      { title: 'Savoir aimer', artist: 'Florent Pagny' },
      { title: 'Aline', artist: 'Christophe' },
      { title: 'L\'Été indien', artist: 'Joe Dassin' },
      { title: 'Foule sentimentale', artist: 'Alain Souchon' }
    ]
  }
];

export function getCategoryById(id) {
  return CATEGORIES.find(cat => cat.id === id) || CATEGORIES[0];
}
