// Définition des catégories de Blind Test et de leurs morceaux/artistes cultes

export const CATEGORIES = [
  {
    id: 'custom_theme',
    name: 'Thème Libre (IA)',
    icon: '✨',
    color: '#ffd200',
    description: 'Tapez votre propre thème ou délire sur-mesure !',
    isCustom: true,
    country: 'FR',
    queries: [
      'Queen', 'Daft Punk', 'Michael Jackson', 'Eminem', 'Stromae',
      'Indochine', 'Ed Sheeran', 'The Weeknd', 'Jul', 'Orelsan',
      'ABBA', 'Bee Gees', 'David Bowie', 'Elton John', 'Beyonce',
      'Coldplay', 'Bruno Mars', 'Dua Lipa', 'Rihanna', 'Katy Perry',
      'Lady Gaga', 'Avicii', 'Angèle', 'Gims', 'Kendji Girac'
    ],
    decoys: [
      { title: 'Bohemian Rhapsody', artist: 'Queen' },
      { title: 'One More Time', artist: 'Daft Punk' },
      { title: 'Billie Jean', artist: 'Michael Jackson' },
      { title: 'Lose Yourself', artist: 'Eminem' },
      { title: 'Shape of You', artist: 'Ed Sheeran' },
      { title: 'Blinding Lights', artist: 'The Weeknd' },
      { title: 'Tous les mêmes', artist: 'Stromae' },
      { title: 'L\'Aventurier', artist: 'Indochine' },
      { title: 'Stayin\' Alive', artist: 'Bee Gees' },
      { title: 'Rolling in the Deep', artist: 'Adele' },
      { title: 'Uptown Funk', artist: 'Bruno Mars' },
      { title: 'Dancing Queen', artist: 'ABBA' },
      { title: 'Get Lucky', artist: 'Daft Punk' },
      { title: 'Bad Romance', artist: 'Lady Gaga' },
      { title: 'Wake Me Up', artist: 'Avicii' },
      { title: 'Balance ton quoi', artist: 'Angèle' },
      { title: 'Can\'t Stop the Feeling!', artist: 'Justin Timberlake' },
      { title: 'Titanium', artist: 'David Guetta & Sia' },
      { title: 'Happy', artist: 'Pharrell Williams' },
      { title: 'Locked Out of Heaven', artist: 'Bruno Mars' }
    ]
  },
  {
    id: 'rap_fr',
    name: 'Rap Français',
    icon: '🔥',
    color: '#ff0055',
    description: 'De NTM et IAM jusqu\'à Jul, Orelsan, PNL et Ninho',
    aiTheme: 'Le meilleur du rap français, des pionniers des années 90 aux têtes d\'affiche actuelles',
    country: 'FR',
    queries: [
      'Jul bande organisée', 'Orelsan la terre est ronde', 'PNL au dd',
      'Ninho lettre a une femme', 'Booba dkr', 'Damso macarena',
      'Nekfeu on verra', 'IAM le mia', 'Suprême NTM seine saint denis style',
      'Soprano en feu', 'SCH bande organisée', 'MC Solaar caroline',
      'Disiz j\'pète les plombs', 'Gazo die', 'Gims bella', 'Vald desaccordes',
      'Aya Nakamura djadja', 'Kaaris tchoin', 'Heuss l\'enfoire moulaga', 'PLK un peu de haine',
      'Dinos helsinki', 'Josman j\'aime bien', 'Tiakola meuda', 'Werenoi laboratoire',
      'SDM bolide allemand', 'Kery James le retour du rap francais', 'Sniper graves dans la roche',
      'Sexion d\'Assaut desole', 'Gringe qui dit mieux', 'Doc Gyneco viens voir le docteur',
      'Lomepal yeux disent', 'Hamza fade up', 'Maes madrina', 'Gradur sheguey',
      'Alonzo batard', 'Lacrim corleone', 'Freeze Corleone freeze rael', 'Rohff qui est l\'exemple'
    ],
    decoys: [
      { title: 'Bande organisée', artist: '13 Organisé' },
      { title: 'La terre est ronde', artist: 'Orelsan' },
      { title: 'Au DD', artist: 'PNL' },
      { title: 'Lettre à une femme', artist: 'Ninho' },
      { title: 'DKR', artist: 'Booba' },
      { title: 'Macarena', artist: 'Damso' },
      { title: 'On verra', artist: 'Nekfeu' },
      { title: 'Je danse le Mia', artist: 'IAM' },
      { title: 'Seine Saint-Denis Style', artist: 'Suprême NTM' },
      { title: 'Caroline', artist: 'MC Solaar' },
      { title: 'J\'pète les plombs', artist: 'Disiz' },
      { title: 'Djadja', artist: 'Aya Nakamura' },
      { title: 'Bella', artist: 'Gims' },
      { title: 'Die', artist: 'Gazo' },
      { title: 'Désaccordé', artist: 'Vald' },
      { title: 'Bolide allemand', artist: 'SDM' },
      { title: 'Désolé', artist: 'Sexion d\'Assaut' },
      { title: 'Yeux disent', artist: 'Lomepal' },
      { title: 'Fade Up', artist: 'Zeg P, Hamza & SCH' },
      { title: 'Madrina', artist: 'Maes ft. Booba' },
      { title: 'Moulaga', artist: 'Heuss L\'enfoiré & Jul' },
      { title: 'Un peu de haine', artist: 'PLK' },
      { title: 'Gravé dans la roche', artist: 'Sniper' },
      { title: 'Viens voir le docteur', artist: 'Doc Gynéco' },
      { title: 'Tchoin', artist: 'Kaaris' },
      { title: 'En feu', artist: 'Soprano' },
      { title: 'Basique', artist: 'Orelsan' },
      { title: '911', artist: 'Damso' },
      { title: 'Deux Frères', artist: 'PNL' },
      { title: 'Tout le monde veut un feat', artist: 'Ninho' }
    ]
  },
  {
    id: 'annees_80',
    name: 'Années 80',
    icon: '🕺',
    color: '#ff00d4',
    description: 'Les plus grands tubes disco, synthwave et new-wave',
    aiTheme: 'Les plus grands tubes des années 80 : disco, pop internationale, synthwave, new-wave et variété française 80s',
    country: 'FR',
    queries: [
      'Michael Jackson billie jean', 'Madonna like a virgin', 'Indochine l aventurier',
      'Balavoine tous les cris les sos', 'Debut de soiree nuit de folie', 'Queen another one bites the dust',
      'Cyndi Lauper girls just want to have fun', 'Gilbert Montagne sous les sunlights des tropiques',
      'Wham wake me up before you go go', 'A-ha take on me', 'Gold ville de lumiere',
      'Eurythmics sweet dreams', 'Desireless voyage voyage', 'Partenaire Particulier',
      'Emile et Images les demons de minuit', 'Jean Schultheis confiance pour confiance',
      'Earth Wind and Fire let s groove', 'Rick Astley never gonna give you up',
      'Niagara l amour a la plage', 'Jeanne Mas en rouge et noir', 'Renaud morgane de toi',
      'Cookie Dingler femme liberee', 'Kool and the Gang celebration', 'Bonnie Tyler total eclipse of the heart',
      'George Michael careless whisper', 'The Police every breath you take',
      'Alphaville big in japan', 'Tears for Fears everybody wants to rule the world',
      'Kylie Minogue the locomotion', 'Modern Talking you\'re my heart you\'re my soul'
    ],
    decoys: [
      { title: 'Billie Jean', artist: 'Michael Jackson' },
      { title: 'Like a Virgin', artist: 'Madonna' },
      { title: 'L\'Aventurier', artist: 'Indochine' },
      { title: 'Tous les cris les S.O.S', artist: 'Daniel Balavoine' },
      { title: 'Nuit de folie', artist: 'Début de Soirée' },
      { title: 'Sweet Dreams', artist: 'Eurythmics' },
      { title: 'Take On Me', artist: 'A-ha' },
      { title: 'Les Démons de minuit', artist: 'Émile et Images' },
      { title: 'Voyage Voyage', artist: 'Desireless' },
      { title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper' },
      { title: 'Wake Me Up Before You Go-Go', artist: 'Wham!' },
      { title: 'Never Gonna Give You Up', artist: 'Rick Astley' },
      { title: 'En rouge et noir', artist: 'Jeanne Mas' },
      { title: 'Sous les sunlights des tropiques', artist: 'Gilbert Montagné' },
      { title: 'Femme libérée', artist: 'Cookie Dingler' },
      { title: 'Every Breath You Take', artist: 'The Police' },
      { title: 'Total Eclipse of the Heart', artist: 'Bonnie Tyler' },
      { title: 'Careless Whisper', artist: 'George Michael' },
      { title: 'Partenaire Particulier', artist: 'Partenaire Particulier' },
      { title: 'L\'amour à la plage', artist: 'Niagara' },
      { title: 'Ville de lumière', artist: 'Gold' },
      { title: 'Celebration', artist: 'Kool & The Gang' },
      { title: 'Another One Bites the Dust', artist: 'Queen' },
      { title: 'Big in Japan', artist: 'Alphaville' },
      { title: 'Thriller', artist: 'Michael Jackson' },
      { title: 'Material Girl', artist: 'Madonna' },
      { title: 'Casser la voix', artist: 'Patrick Bruel' }
    ]
  },
  {
    id: 'annees_90_2000',
    name: 'Années 90 & 2000',
    icon: '💿',
    color: '#00f2fe',
    description: 'L\'âge d\'or MTV, les boys bands, l\'eurodance et les hymnes 2000',
    aiTheme: 'Les hymnes inoubliables des années 90 et 2000 : eurodance, pop MTV, boys bands, pop-rock et RnB 2000',
    country: 'FR',
    queries: [
      'Britney Spears baby one more time', 'Daft Punk one more time', 'Eminem without me',
      'Manau la tribu de dana', 'Kyo derniere danse', 'Diams la boulette',
      'Shakira whenever wherever', 'Beyonce crazy in love', 'Louise Attaque j t emmene au vent',
      'Black Eyed Peas i gotta feeling', 'Linkin Park in the end', 'Avril Lavigne complicated',
      'Rihanna umbrella', 'Alizee moi lolita', 'Celine Dion pour que tu m aimes encore',
      'Gala freed from desire', 'Corona the rhythm of the night', 'Coolio gangsta s paradise',
      'Destiny s Child survivor', 'Outkast hey ya', 'Backstreet Boys everybody',
      'Aqua barbie girl', 'Lou Bega mambo no 5', 'Tragedie est ce que tu m entends',
      'Rednex cotton eye joe', 'Willy Denzey le mur du son', 'Yannick ces soirees la',
      'Superbus butterfly', 'O-Zone dragostea din tei', 'Cascada everytimer we touch'
    ],
    decoys: [
      { title: '...Baby One More Time', artist: 'Britney Spears' },
      { title: 'One More Time', artist: 'Daft Punk' },
      { title: 'Without Me', artist: 'Eminem' },
      { title: 'La Tribu de Dana', artist: 'Manau' },
      { title: 'Dernière danse', artist: 'Kyo' },
      { title: 'La Boulette', artist: 'Diam\'s' },
      { title: 'Whenever, Wherever', artist: 'Shakira' },
      { title: 'Crazy in Love', artist: 'Beyoncé' },
      { title: 'In the End', artist: 'Linkin Park' },
      { title: 'I Gotta Feeling', artist: 'Black Eyed Peas' },
      { title: 'Moi... Lolita', artist: 'Alizée' },
      { title: 'Freed from Desire', artist: 'Gala' },
      { title: 'J\'t\'emmène au vent', artist: 'Louise Attaque' },
      { title: 'Hey Ya!', artist: 'OutKast' },
      { title: 'Barbie Girl', artist: 'Aqua' },
      { title: 'Gangsta\'s Paradise', artist: 'Coolio' },
      { title: 'Pour que tu m\'aimes encore', artist: 'Céline Dion' },
      { title: 'Everybody (Backstreet\'s Back)', artist: 'Backstreet Boys' },
      { title: 'Est-ce que tu m\'entends ?', artist: 'Tragédie' },
      { title: 'Ces soirées-là', artist: 'Yannick' },
      { title: 'Umbrella', artist: 'Rihanna' },
      { title: 'Complicated', artist: 'Avril Lavigne' },
      { title: 'Survivor', artist: 'Destiny\'s Child' },
      { title: 'Dragostea Din Tei', artist: 'O-Zone' },
      { title: 'Mambo No. 5', artist: 'Lou Bega' },
      { title: 'The Rhythm of the Night', artist: 'Corona' },
      { title: 'Toxic', artist: 'Britney Spears' },
      { title: 'Around the World', artist: 'Daft Punk' }
    ]
  },
  {
    id: 'rock_classics',
    name: 'Rock Classics',
    icon: '🎸',
    color: '#ff9900',
    description: 'Riffs légendaires, solos mythiques et légendes du rock',
    aiTheme: 'Les grands classiques du rock : rock légendaire, hard rock, grunge, pop rock et hymnes de stade',
    country: 'US',
    queries: [
      'Queen bohemian rhapsody', 'AC DC highway to hell', 'Nirvana smells like teen spirit',
      'The Beatles let it be', 'Rolling Stones paint it black', 'Pink Floyd another brick in the wall',
      'Guns N Roses sweet child o mine', 'Red Hot Chili Peppers californication', 'Telephone ca c est vraiment toi',
      'Oasis wonderwall', 'Led Zeppelin stairway to heaven', 'The Cranberries zombie',
      'Deep Purple smoke on the water', 'The Police roxanne', 'U2 with or without you',
      'Bon Jovi livin on a prayer', 'Scorpions wind of change', 'Dire Straits sultans of swing',
      'Aerosmith dream on', 'Metallica enter sandman', 'The Clash should i stay or should i go',
      'Green Day basket case', 'Blink-182 all the small things', 'Foo Fighters everlong',
      'Radiohead creep', 'Linkin Park numb', 'The White Stripes seven nation army',
      'Muse plug in baby', 'The Killers mr brightside', 'Joan Jett i love rock n roll'
    ],
    decoys: [
      { title: 'Bohemian Rhapsody', artist: 'Queen' },
      { title: 'Highway to Hell', artist: 'AC/DC' },
      { title: 'Smells Like Teen Spirit', artist: 'Nirvana' },
      { title: 'Paint It Black', artist: 'The Rolling Stones' },
      { title: 'Sweet Child O\' Mine', artist: 'Guns N\' Roses' },
      { title: 'Californication', artist: 'Red Hot Chili Peppers' },
      { title: 'Wonderwall', artist: 'Oasis' },
      { title: 'Stairway to Heaven', artist: 'Led Zeppelin' },
      { title: 'Zombie', artist: 'The Cranberries' },
      { title: 'Smoke on the Water', artist: 'Deep Purple' },
      { title: 'Ça (C\'est vraiment toi)', artist: 'Téléphone' },
      { title: 'Livin\' on a Prayer', artist: 'Bon Jovi' },
      { title: 'Basket Case', artist: 'Green Day' },
      { title: 'Seven Nation Army', artist: 'The White Stripes' },
      { title: 'Creep', artist: 'Radiohead' },
      { title: 'Enter Sandman', artist: 'Metallica' },
      { title: 'Should I Stay or Should I Go', artist: 'The Clash' },
      { title: 'Sultans of Swing', artist: 'Dire Straits' },
      { title: 'Wind of Change', artist: 'Scorpions' },
      { title: 'All the Small Things', artist: 'Blink-182' },
      { title: 'Roxanne', artist: 'The Police' },
      { title: 'With or Without You', artist: 'U2' },
      { title: 'I Love Rock \'n\' Roll', artist: 'Joan Jett' },
      { title: 'Let It Be', artist: 'The Beatles' },
      { title: 'Back in Black', artist: 'AC/DC' },
      { title: 'We Will Rock You', artist: 'Queen' }
    ]
  },
  {
    id: 'pop_internationale',
    name: 'Pop Internationale',
    icon: '✨',
    color: '#9d00ff',
    description: 'Les méga-hits mondiaux qui cartonnent sur toutes les radios',
    aiTheme: 'Les méga-hits de la pop internationale moderne des années 2010 à aujourd\'hui',
    country: 'US',
    queries: [
      'Taylor Swift shake it off', 'The Weeknd blinding lights', 'Dua Lipa levitating',
      'Bruno Mars uptown funk', 'Billie Eilish bad guy', 'Ed Sheeran shape of you',
      'Ariana Grande 7 rings', 'Coldplay viva la vida', 'Harry Styles as it was',
      'Sia chandelier', 'Justin Bieber stay', 'Katy Perry roar',
      'Lady Gaga bad romance', 'Miley Cyrus flowers', 'Imagine Dragons radioactive',
      'Maroon 5 sugar', 'Adele rolling in the deep', 'Stromae alors on danse',
      'Shawn Mendes senorita', 'Sam Smith stay with me', 'Post Malone circles',
      'Lizzo about damn time', 'Olivia Rodrigo drivers license', 'Camila Cabello havana',
      'Beyonce single ladies', 'Rihanna diamonds', 'Avicii wake me up',
      'Pitbull give me everything', 'David Guetta titanium', 'Justin Timberlake can\'t stop the feeling'
    ],
    decoys: [
      { title: 'Shake It Off', artist: 'Taylor Swift' },
      { title: 'Blinding Lights', artist: 'The Weeknd' },
      { title: 'Levitating', artist: 'Dua Lipa' },
      { title: 'Uptown Funk', artist: 'Bruno Mars' },
      { title: 'Bad Guy', artist: 'Billie Eilish' },
      { title: 'Shape of You', artist: 'Ed Sheeran' },
      { title: 'As It Was', artist: 'Harry Styles' },
      { title: 'Viva La Vida', artist: 'Coldplay' },
      { title: 'Chandelier', artist: 'Sia' },
      { title: 'Flowers', artist: 'Miley Cyrus' },
      { title: 'Bad Romance', artist: 'Lady Gaga' },
      { title: 'Rolling in the Deep', artist: 'Adele' },
      { title: 'Havana', artist: 'Camila Cabello' },
      { title: '7 rings', artist: 'Ariana Grande' },
      { title: 'Stay', artist: 'The Kid LAROI & Justin Bieber' },
      { title: 'Roar', artist: 'Katy Perry' },
      { title: 'Radioactive', artist: 'Imagine Dragons' },
      { title: 'Sugar', artist: 'Maroon 5' },
      { title: 'Diamonds', artist: 'Rihanna' },
      { title: 'Single Ladies', artist: 'Beyoncé' },
      { title: 'Drivers License', artist: 'Olivia Rodrigo' },
      { title: 'Circles', artist: 'Post Malone' },
      { title: 'Señorita', artist: 'Shawn Mendes & Camila Cabello' },
      { title: 'Starboy', artist: 'The Weeknd' },
      { title: 'Someone Like You', artist: 'Adele' }
    ]
  },
  {
    id: 'disney_dessins_animes',
    name: 'Disney & Enfance',
    icon: '🏰',
    color: '#00e5ff',
    description: 'Les plus beaux classiques d\'animation Disney et génériques cultes',
    aiTheme: 'Les plus grandes chansons de films d\'animation Disney et génériques cultes en version française',
    country: 'FR',
    queries: [
      'Disney le roi lion histoire de la vie',
      'Disney la reine des neiges liberee delivree',
      'Disney aladdin ce reve bleu',
      'Disney tarzan entre deux mondes',
      'Pokemon un jour je serai le meilleur dresseur',
      'Disney hercule de zero en heros',
      'Disney vaiana le bleu lumiere',
      'Disney mulan comme un homme',
      'Disney le livre de la jungle il en faut peu pour etre heureux',
      'Disney la belle et la bete c est la fete',
      'Disney raiponce ou est la vraie vie',
      'Les Mysterieuses Cites d or generique',
      'Disney encanto ne parlons pas de bruno',
      'Disney la petite sirene sous l ocean',
      'Disney pocahontas l air du vent',
      'Disney les aristochats tout le monde veut devenir un cat',
      'Disney toy story je suis ton ami',
      'Disney cendrillon bibbidi bobbidi boo',
      'Disney la princesse et la grenouille au bout du reve',
      'Disney pinocchio quand on prie la bonne etoile',
      'Disney zootopie try everything',
      'Disney aladdin prince ali',
      'Disney le roi lion hakuna matata',
      'Disney mulan reflexion',
      'Disney hercule jamais je n avouerai',
      'Disney coco ne m oublie pas',
      'Disney la petite sirene partir la bas',
      'Capitaine Flam generique',
      'Inspecteur Gadget generique',
      'Olive et Tom generique'
    ],
    decoys: [
      { title: 'L\'Histoire de la vie', artist: 'Le Roi Lion', movie: 'Le Roi Lion' },
      { title: 'Ce rêve bleu', artist: 'Aladdin', movie: 'Aladdin' },
      { title: 'Libérée, délivrée', artist: 'La Reine des Neiges', movie: 'La Reine des Neiges' },
      { title: 'Il en faut peu pour être heureux', artist: 'Le Livre de la Jungle', movie: 'Le Livre de la Jungle' },
      { title: 'Comme un homme', artist: 'Mulan', movie: 'Mulan' },
      { title: 'Sous l\'océan', artist: 'La Petite Sirène', movie: 'La Petite Sirène' },
      { title: 'Hakuna Matata', artist: 'Le Roi Lion', movie: 'Le Roi Lion' },
      { title: 'Le Bleu lumière', artist: 'Vaiana', movie: 'Vaiana' },
      { title: 'Être un homme comme vous', artist: 'Le Livre de la Jungle', movie: 'Le Livre de la Jungle' },
      { title: 'Histoire éternelle', artist: 'La Belle et la Bête', movie: 'La Belle et la Bête' },
      { title: 'Tout le monde veut devenir un cat', artist: 'Les Aristochats', movie: 'Les Aristochats' },
      { title: 'De zéro en héros', artist: 'Hercule', movie: 'Hercule' },
      { title: 'L\'Air du vent', artist: 'Pocahontas', movie: 'Pocahontas' },
      { title: 'Je suis ton ami', artist: 'Toy Story', movie: 'Toy Story' },
      { title: 'Ne parlons pas de Bruno', artist: 'Encanto', movie: 'Encanto' },
      { title: 'Attrapez-les tous !', artist: 'Pokémon', movie: 'Pokémon' },
      { title: 'Prince Ali', artist: 'Aladdin', movie: 'Aladdin' },
      { title: 'Partir là-bas', artist: 'La Petite Sirène', movie: 'La Petite Sirène' },
      { title: 'Où est la vraie vie ?', artist: 'Raiponce', movie: 'Raiponce' },
      { title: 'Entre deux mondes', artist: 'Tarzan', movie: 'Tarzan' },
      { title: 'Ne m\'oublie pas', artist: 'Coco', movie: 'Coco' },
      { title: 'C\'est la fête', artist: 'La Belle et la Bête', movie: 'La Belle et la Bête' },
      { title: 'Bibbidi-Bobbidi-Boo', artist: 'Cendrillon', movie: 'Cendrillon' },
      { title: 'L\'amour brille sous les étoiles', artist: 'Le Roi Lion', movie: 'Le Roi Lion' },
      { title: 'Je voudrais un bonhomme de neige', artist: 'La Reine des Neiges', movie: 'La Reine des Neiges' }
    ]
  },
  {
    id: 'cinema_series',
    name: 'Cinéma & Séries',
    icon: '🎬',
    color: '#e6c800',
    description: 'Bandes originales légendaires du grand et du petit écran',
    aiTheme: 'Les bandes originales et thèmes musicaux cultes du cinéma et des séries TV',
    country: 'US',
    queries: [
      'John Williams star wars main theme', 'Hans Zimmer pirates of the caribbean',
      'John Williams harry potter hedwig theme', 'Ramin Djawadi game of thrones',
      'Hans Zimmer gladiator now we are free', 'Howard Shore the lord of the rings concerning hobbits',
      'Hans Zimmer interstellar main theme', 'Ennio Morricone the good the bad and the ugly',
      'John Williams jurassic park theme', 'Monty Norman james bond theme',
      'Alan Silvestri the avengers theme', 'Clint Mansell requiem for a dream lux aeterna',
      'Brad Fiedel the terminator theme', 'John Williams indiana jones theme',
      'Lalo Schifrin mission impossible theme', 'Henry Mancini pink panther theme',
      'Vangelis chariots of fire', 'Bill Conti rocky gonna fly now',
      'Celine Dion titanic my heart will go on', 'Survivor rocky eye of the tiger',
      'Ray Parker Jr ghostbusters', 'Adele skyfall', 'Kenny Loggins top gun danger zone',
      'Dick Dale pulp fiction misirlou', 'Simon & Garfunkel the graduate sound of silence'
    ],
    decoys: [
      { title: 'Star Wars (Main Theme)', artist: 'John Williams', movie: 'Star Wars' },
      { title: 'He\'s a Pirate', artist: 'Hans Zimmer & Klaus Badelt', movie: 'Pirates des Caraïbes' },
      { title: 'Hedwig\'s Theme', artist: 'John Williams', movie: 'Harry Potter' },
      { title: 'Game of Thrones (Main Theme)', artist: 'Ramin Djawadi', movie: 'Game of Thrones' },
      { title: 'Now We Are Free', artist: 'Hans Zimmer & Lisa Gerrard', movie: 'Gladiator' },
      { title: 'Concerning Hobbits', artist: 'Howard Shore', movie: 'Le Seigneur des Anneaux' },
      { title: 'The Pink Panther Theme', artist: 'Henry Mancini', movie: 'La Panthère Rose' },
      { title: 'James Bond Theme', artist: 'Monty Norman', movie: 'James Bond' },
      { title: 'Mission Impossible Theme', artist: 'Lalo Schifrin', movie: 'Mission Impossible' },
      { title: 'The Good, the Bad and the Ugly', artist: 'Ennio Morricone', movie: 'Le Bon, la Brute et le Truand' },
      { title: 'Jurassic Park Theme', artist: 'John Williams', movie: 'Jurassic Park' },
      { title: 'The Avengers Theme', artist: 'Alan Silvestri', movie: 'Avengers' },
      { title: 'My Heart Will Go On', artist: 'Céline Dion', movie: 'Titanic' },
      { title: 'Eye of the Tiger', artist: 'Survivor', movie: 'Rocky' },
      { title: 'Ghostbusters', artist: 'Ray Parker Jr.', movie: 'SOS Fantômes' },
      { title: 'Skyfall', artist: 'Adele', movie: 'James Bond Skyfall' },
      { title: 'Danger Zone', artist: 'Kenny Loggins', movie: 'Top Gun' },
      { title: 'Misirlou', artist: 'Dick Dale', movie: 'Pulp Fiction' },
      { title: 'Lux Aeterna', artist: 'Clint Mansell', movie: 'Requiem for a Dream' },
      { title: 'Interstellar Theme', artist: 'Hans Zimmer', movie: 'Interstellar' },
      { title: 'Indiana Jones Theme', artist: 'John Williams', movie: 'Indiana Jones' },
      { title: 'Gonna Fly Now', artist: 'Bill Conti', movie: 'Rocky' }
    ]
  },
  {
    id: 'variete_francaise',
    name: 'Variété Française',
    icon: '🍷',
    color: '#00d26a',
    description: 'Les grands classiques de la chanson et du patrimoine français',
    aiTheme: 'Les grands classiques incontournables du patrimoine de la chanson et variété française',
    country: 'FR',
    queries: [
      'Jean-Jacques Goldman envole-moi', 'Renaud des que le vent soufflera',
      'Francis Cabrel la corrida', 'Johnny Hallyday allumer le feu',
      'Charles Aznavour la boheme', 'Daniel Balavoine je ne suis pas un heros',
      'Michel Sardou les lacs du connemara', 'Jacques Brel ne me quitte pas',
      'Claude Francois alexandrie alexandra', 'Vianney beau-papa',
      'Florent Pagny savoir aimer', 'Christophe aline', 'Michel Polnareff lettre a france',
      'Serge Gainsbourg la javanaise', 'Joe Dassin l ete indien', 'Maxime Le Forestier san francisco',
      'Patrick Bruel casser la voix', 'Julien Clerc ma preference', 'Alain Souchon foule sentimentale',
      'France Gall il jouait du piano debout', 'Michel Berger la groupie du pianiste',
      'Laurent Voulzy rockollection', 'Eddy Mitchell sur la route de memphis',
      'Georges Brassens les copains d abord', 'Edith Piaf non je ne regrette rien'
    ],
    decoys: [
      { title: 'Envole-moi', artist: 'Jean-Jacques Goldman' },
      { title: 'Dès que le vent soufflera', artist: 'Renaud' },
      { title: 'La Corrida', artist: 'Francis Cabrel' },
      { title: 'Allumer le feu', artist: 'Johnny Hallyday' },
      { title: 'La Bohème', artist: 'Charles Aznavour' },
      { title: 'Je ne suis pas un héros', artist: 'Daniel Balavoine' },
      { title: 'Les Lacs du Connemara', artist: 'Michel Sardou' },
      { title: 'Ne me quitte pas', artist: 'Jacques Brel' },
      { title: 'Alexandrie Alexandra', artist: 'Claude François' },
      { title: 'Savoir aimer', artist: 'Florent Pagny' },
      { title: 'Aline', artist: 'Christophe' },
      { title: 'L\'Été indien', artist: 'Joe Dassin' },
      { title: 'Foule sentimentale', artist: 'Alain Souchon' },
      { title: 'La Javanaise', artist: 'Serge Gainsbourg' },
      { title: 'Il jouait du piano debout', artist: 'France Gall' },
      { title: 'La Groupie du pianiste', artist: 'Michel Berger' },
      { title: 'Rockollection', artist: 'Laurent Voulzy' },
      { title: 'Casser la voix', artist: 'Patrick Bruel' },
      { title: 'Lettre à France', artist: 'Michel Polnareff' },
      { title: 'Non, je ne regrette rien', artist: 'Édith Piaf' },
      { title: 'Les Copains d\'abord', artist: 'Georges Brassens' },
      { title: 'San Francisco', artist: 'Maxime Le Forestier' },
      { title: 'Je te promets', artist: 'Johnny Hallyday' },
      { title: 'Je l\'aime à mourir', artist: 'Francis Cabrel' }
    ]
  }
];

export function getCategoryById(id) {
  return CATEGORIES.find(cat => cat.id === id) || CATEGORIES[0];
}
